import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getCache, ttl } from "@/lib/cache/redis";
import { loadLatestXBrief, type XBrief } from "@/lib/x";
import { XPage } from "@/components/stack/XPage";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// Dedicated X / Twitter section: the "On X today" brief (generated by
// /api/jobs/x-brief from the tweet clusters/posts) with inline citation chips
// into the source posts on X. The cluster data still drives the brief + its
// citations server-side; we just don't render a separate grid here.
export default async function X() {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return <XPage brief={null} citations={null} />;
  }

  const supabase = await createSupabaseServerClient();
  const cache = getCache();

  const brief = await cache.remember<XBrief | null>(
    "x:brief:v1",
    ttl.stories,
    () => loadLatestXBrief(supabase),
  );

  return <XPage brief={brief?.markdown ?? null} citations={brief?.citations ?? null} />;
}
