import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getCache, ttl } from "@/lib/cache/redis";
import { loadLatestNewsBrief, type NewsBrief } from "@/lib/news-brief";
import { BriefPage } from "@/components/stack/BriefPage";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// "What's going on in AI Space" — the ranked daily news brief (releases,
// funding, research, product, policy) generated by /api/jobs/news-brief from the
// top trending items, with inline citation chips into each story's source. The
// news counterpart to /x.
export default async function Brief() {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return <BriefPage brief={null} />;
  }

  const supabase = await createSupabaseServerClient();
  const cache = getCache();

  const brief = await cache.remember<NewsBrief | null>(
    "news:brief:v1",
    ttl.stories,
    () => loadLatestNewsBrief(supabase),
  );

  return <BriefPage brief={brief} />;
}
